version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: get4domain_frontend
    restart: unless-stopped
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
    networks:
      - get4domain_net

networks:
  get4domain_net:
    driver: bridge
