// Turns scripts/bos/audit.js output (audit.json) into docs/v2/evidence/full-bos/AUDIT_<date>.md.
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '..', '..', '..', 'docs', 'v2', 'evidence', 'full-bos');
const a = JSON.parse(fs.readFileSync(path.join(dir, 'audit.json'), 'utf8'));
const date = a.generatedAt.slice(0, 10);
const counts = a.rows.reduce((m, r) => ({ ...m, [r.result]: (m[r.result] ?? 0) + 1 }), {});
const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const L = [];
L.push(`# Full BOS audit — did it work or not (${date})`);
L.push('');
L.push('Method: the real compiled API over an isolated in-memory Postgres (`backend-api/scripts/bos/audit.js`, re-runnable), one seeded COMMERCE vendor shaped like Step N Rock (footwear: products with sizes/colours, tracked stock, website, a website order). Nothing was fixed while auditing. UI-only facts come from the production-build walkthrough in `docs/v2/evidence/dashboard-v2/WALKTHROUGH.md` and from reading the code, and are marked as such.');
L.push('');
L.push(`**Counts over ${a.rows.length} registry features:** WORKS ${counts.WORKS ?? 0} · PARTIAL ${counts.PARTIAL ?? 0} · BROKEN ${counts.BROKEN ?? 0} · NOT BUILT ${counts['NOT BUILT'] ?? 0}.`);
L.push('');
L.push('## Plain answer: did products work?');
L.push('');
L.push('**Selling works, billing and books do not.** A product created in My Products shows on the website, can be put in a cart, becomes an order, reserves stock exactly once, and the owner can mark it paid. Stock history is a real ledger. After that the chain stops: the order creates a CRM lead but **no customer record**, nothing turns an order into a customer invoice, there are no receipts, part payments, outstanding amounts or credit notes, website sales carry no GST, and the Accounts screen cannot see a paid website order (it reads manual invoices only). There are **three separate product stores**; only one of them feeds the website, orders and stock.');
L.push('');
L.push('## Chains, step by step');
const names = { A: 'Chain A — Sell', B: 'Chain B — Bill', C: 'Chain C — Stock', D: 'Chain D — Books', E: 'Chain E — The product stores' };
for (const k of ['A', 'B', 'C', 'D', 'E']) {
  L.push('');
  L.push(`### ${names[k]}`);
  L.push('');
  L.push('| Step | Result | Evidence |');
  L.push('|---|---|---|');
  for (const s of a.chains[k]) L.push(`| ${esc(s.step)} | ${s.ok ? 'works' : '**BREAKS HERE**'} | ${esc(s.evidence)} |`);
}
L.push('');
L.push('**Where each chain breaks:** A at A5 (no customer record from an order). B at B1 (no order→invoice), B3 (share link fails with a raw 500 "Authentication failed" when the vendor has no gateway keys), B5/B6 (no receipts, no outstanding, no credit notes). C at C5/C6 (no variants, no locations, no purchases). D at D1–D4 (books blind to website sales; no ledger, no GST). E: three stores that disagree (see E2–E5).');
L.push('');
L.push('### Chain E — which store feeds what');
L.push('');
L.push('| Store (table) | Website | My Products | Orders (price/stock) | Stock screen | Invoices | POS |');
L.push('|---|---|---|---|---|---|---|');
L.push('| `VendorProduct` (the universal catalogue) | yes | yes | yes | yes | no link (free-text invoice lines) | no |');
L.push('| `g4d_catalog_items` (`CatalogItem`) | no | no | no | no | records only | no |');
L.push('| `g4d_retail_products` (`RetailProduct`) | no | no | no | no | no | yes (its own stock) |');
L.push('');
L.push('## Known bugs reproduced');
L.push('');
L.push(`- **B1 Website Manager save:** ${a.bugs.B1.reproduced ? 'REPRODUCED' : 'not reproduced'} — saving back what the screen loaded returns HTTP ${a.bugs.B1.status}: \`${esc(a.bugs.B1.message)}\`. Cause: the form sends read-only fields (id, vendorId, createdAt, updatedAt, businessHours) and the API refuses unknown properties.`);
L.push('- **B2 Razorpay Key ID shows an e-mail:** cause found in code: the Key ID is a plain text input directly before a password input with no `autocomplete` attributes, so the browser fills the saved login e-mail into it (`app/dashboard/payments/page.tsx`). The server stores whatever text it is given with no format check. Whether any live vendor row already holds a non-`rzp_` value cannot be read from here (the audit never touches production): `backend-api/scripts/bos/razorpay-key-report.js` is a read-only report for KSM to run on the VM.');
L.push('- **B3 AI credit ₹250 vs ₹499:** `go-live/page.tsx` hard-codes "₹499 / ₹1,299 AI Studio credit included" (the annual list amount) while the vendor term shows the prorated credit for its length (₹250 for a half-year Essentials term). Several marketing pages repeat the annual figures. One source of truth is needed.');
L.push('');
L.push('## One row per registry feature');
L.push('');
L.push('feature id | department | what was tested | result | evidence | fix size');
L.push('---|---|---|---|---|---');
for (const r of a.rows) L.push(`${r.id} | ${r.department ?? r.dept} | ${esc(r.tested)} | ${r.result} | ${esc(r.evidence)} | ${r.size}`);
L.push('');
L.push('Size key: S = under a day, M = a few days, L = about a week or more, XL = a project.');
fs.writeFileSync(path.join(dir, `AUDIT_${date}.md`), L.join('\n') + '\n');
console.log('wrote', `AUDIT_${date}.md`, counts);
