'use client';

import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Loader2, QrCode, Upload } from 'lucide-react';
import Button from '@/components/ui/Button';
import { api } from '@/lib/api';
import { commerceApi } from '@/lib/commerce';
import { ErrorBox, Field, cardCls, inputCls, msg } from '@/components/admin/commerce-ui';

const EMPTY = { upiId: '', payeeName: '', qrImageUrl: '', bankName: '', bankAccountName: '', bankAccountNumber: '', bankIfsc: '', bankBranch: '', instructions: '' };

export default function PayeePage() {
  const [f, setF] = useState(EMPTY);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState('');
  const [uploading, setUploading] = useState(false);
  const [preview, setPreview] = useState<{ configured: boolean; qrDataUrl?: string; upiLink?: string } | null>(null);

  const loadPreview = useCallback(() => commerceApi.previewPayee().then((r) => setPreview(r.data)).catch(() => setPreview(null)), []);
  useEffect(() => {
    commerceApi.getPayee().then((r) => { const d = (r.data ?? {}) as Record<string, string | null>; setF({ ...EMPTY, ...Object.fromEntries(Object.keys(EMPTY).map((k) => [k, d[k] ?? ''])) }); }).catch((e) => setError(msg(e))).finally(() => setLoading(false));
    void loadPreview();
  }, [loadPreview]);

  async function save(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true); setError(''); setSaved(false);
    try { await commerceApi.updatePayee(Object.fromEntries(Object.entries(f).map(([k, v]) => [k, v.trim() === '' ? null : v.trim()]))); setSaved(true); await loadPreview(); setTimeout(() => setSaved(false), 3000); }
    catch (err) { setError(msg(err)); } finally { setSaving(false); }
  }
  async function uploadQr(file: File) {
    setUploading(true); setError('');
    try { const r = await api.uploadImage(file); if (r.data?.url) setF((cur) => ({ ...cur, qrImageUrl: r.data!.url })); }
    catch (err) { setError(msg(err)); } finally { setUploading(false); }
  }
  const set = (k: keyof typeof EMPTY) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setF({ ...f, [k]: e.target.value });

  if (loading) return <div className="flex justify-center py-16"><Loader2 className="h-6 w-6 animate-spin text-slate-500" /></div>;

  return (
    <form onSubmit={save} className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]">
      <div className="space-y-5">
        <section className={`${cardCls} space-y-4`}>
          <div><h3 className="text-sm font-bold text-white">UPI</h3><p className="text-xs text-slate-500">Used to build the exact-amount UPI link and QR on every pay page. The QR is generated by the server for each invoice.</p></div>
          <div className="grid gap-3 sm:grid-cols-2">
            <Field label="UPI ID (VPA)" hint="e.g. get4domain@okhdfcbank"><input className={inputCls} value={f.upiId} onChange={set('upiId')} autoComplete="off" /></Field>
            <Field label="Payee name" hint="Shown in the customer's UPI app"><input className={inputCls} value={f.payeeName} onChange={set('payeeName')} maxLength={80} /></Field>
          </div>
          <div>
            <span className="mb-1 block text-xs font-semibold text-slate-400">Static QR image (optional fallback)</span>
            <div className="flex flex-wrap items-center gap-3">
              <label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-slate-600 px-3.5 py-2 text-sm text-slate-300"><Upload className="h-4 w-4" />{uploading ? 'Uploading…' : 'Upload image'}<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={(e) => e.target.files?.[0] && uploadQr(e.target.files[0])} /></label>
              {f.qrImageUrl && <><img src={f.qrImageUrl} alt="Static QR" className="h-16 w-16 rounded-lg border border-slate-700 bg-white object-contain p-1" /><button type="button" className="text-xs text-slate-400 underline" onClick={() => setF({ ...f, qrImageUrl: '' })}>Remove</button></>}
            </div>
            <p className="mt-1 text-[11px] text-slate-500">The static QR is public by design (payers can scan it). It cannot carry an invoice amount — the dynamic QR above can.</p>
          </div>
        </section>

        <section className={`${cardCls} space-y-4`}>
          <div><h3 className="text-sm font-bold text-white">Bank details</h3><p className="text-xs text-slate-500">Shown to payers who choose bank transfer.</p></div>
          <div className="grid gap-3 sm:grid-cols-2">
            <Field label="Bank"><input className={inputCls} value={f.bankName} onChange={set('bankName')} /></Field>
            <Field label="Account name"><input className={inputCls} value={f.bankAccountName} onChange={set('bankAccountName')} /></Field>
            <Field label="Account number"><input inputMode="numeric" className={inputCls} value={f.bankAccountNumber} onChange={set('bankAccountNumber')} /></Field>
            <Field label="IFSC"><input className={`${inputCls} uppercase`} value={f.bankIfsc} onChange={set('bankIfsc')} maxLength={11} /></Field>
            <Field label="Branch" className="sm:col-span-2"><input className={inputCls} value={f.bankBranch} onChange={set('bankBranch')} /></Field>
          </div>
        </section>

        <section className={`${cardCls} space-y-3`}>
          <Field label="Instructions for payers" hint="e.g. “Add the invoice number in the remarks. We confirm payments within 2 working hours.”"><textarea className={`${inputCls} min-h-[5rem]`} value={f.instructions} onChange={set('instructions')} maxLength={1000} /></Field>
        </section>

        <ErrorBox message={error} />
        <div className="flex items-center gap-3"><Button type="submit" loading={saving}>Save payee settings</Button>{saved && <span className="flex items-center gap-1.5 text-sm text-success-400"><CheckCircle2 className="h-4 w-4" />Saved</span>}</div>
      </div>

      <aside className={`${cardCls} h-fit space-y-3 lg:sticky lg:top-4`}>
        <h3 className="flex items-center gap-2 text-sm font-bold text-white"><QrCode className="h-4 w-4" />What payers will scan</h3>
        {preview?.configured && preview.qrDataUrl ? (
          <>
            <div className="mx-auto w-fit rounded-xl bg-white p-3">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={preview.qrDataUrl} alt="Sample UPI QR (₹1.00)" className="h-48 w-48" /></div>
            <p className="text-center text-xs text-slate-400">Sample for ₹1.00, note “PREVIEW”. Real invoices carry their exact balance and invoice number.</p>
            <p className="break-all rounded-lg bg-slate-950 px-2.5 py-2 font-mono text-[10px] text-slate-400">{preview.upiLink}</p>
          </>
        ) : <p className="text-sm text-slate-500">Save a valid UPI ID to see the QR preview. Until then the UPI QR option shows “not set up” on pay pages.</p>}
      </aside>
    </form>
  );
}
