import { ApiProperty } from '@nestjs/swagger';
import { IsInt, IsString, Min } from 'class-validator';

export class DeductDto {
  @ApiProperty()
  @IsString()
  vendorId!: string;

  @ApiProperty({ description: 'Amount to deduct, in paise' })
  @IsInt()
  @Min(1)
  amount!: number;

  @ApiProperty({ example: 'Instagram post generated by AI' })
  @IsString()
  description!: string;

  @ApiProperty({ example: 'ai_image_post' })
  @IsString()
  service!: string;
}
