version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: allwin_tours
    restart: unless-stopped
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
    networks:
      - allwin_tours_net

networks:
  allwin_tours_net:
    driver: bridge
